name: Dev Build and Publish Artifact

on:
  workflow_dispatch: {}
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build the application
      run: dotnet build --configuration Release
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: MonitorSwitch
        path: .\MonitorSwitch\bin\Release\net7.0-windows
